# Generated by Django 3.1.12 on 2026-03-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Store Name')),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion & Apparel'), ('food', 'Food & Beverage'), ('home', 'Home & Living'), ('beauty', 'Beauty & Cosmetics'), ('sports', 'Sports & Fitness'), ('entertainment', 'Entertainment'), ('books', 'Books & Stationery'), ('jewelry', 'Jewelry & Accessories'), ('other', 'Other')], max_length=50, verbose_name='Category')),
                ('location', models.CharField(choices=[('GF-N', 'Ground Floor - North Wing'), ('GF-S', 'Ground Floor - South Wing'), ('GF-E', 'Ground Floor - East Wing'), ('GF-W', 'Ground Floor - West Wing'), ('1F-N', 'First Floor - North Wing'), ('1F-S', 'First Floor - South Wing'), ('1F-E', 'First Floor - East Wing'), ('1F-W', 'First Floor - West Wing'), ('2F-N', 'Second Floor - North Wing'), ('2F-S', 'Second Floor - South Wing'), ('2F-E', 'Second Floor - East Wing'), ('2F-W', 'Second Floor - West Wing')], max_length=50, verbose_name='Location')),
                ('size', models.IntegerField(help_text='Store size in square feet', verbose_name='Store Size (sq. ft.)')),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Monthly rent in Indian Rupees', max_digits=10, verbose_name='Monthly Rent (₹)')),
                ('manager', models.CharField(max_length=200, verbose_name='Store Manager')),
                ('description', models.TextField(blank=True, help_text='Brief description of the store, products/services offered...', verbose_name='Store Description')),
                ('contact_info', models.CharField(help_text='Phone number or email', max_length=200, verbose_name='Contact Information')),
                ('operating_hours', models.CharField(default='10:00 AM - 9:00 PM', max_length=100, verbose_name='Operating Hours')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['store_id'], name='mall_manage_store_i_e3261a_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['category'], name='mall_manage_categor_50f553_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['location'], name='mall_manage_locatio_b54125_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['status'], name='mall_manage_status_fd8dfc_idx'),
        ),
    ]
