# Generated by Django 3.1.12 on 2026-03-05 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mall_management_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('food', 'Food & Beverage'), ('beauty', 'Beauty'), ('sports', 'Sports'), ('home', 'Home & Living'), ('entertainment', 'Entertainment'), ('books', 'Books & Stationery'), ('other', 'Other')], max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('transaction_time', models.TimeField(auto_now_add=True)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('transaction_datetime', models.DateTimeField(auto_now_add=True)),
                ('hour', models.IntegerField(editable=False)),
                ('day_of_week', models.IntegerField(editable=False)),
                ('day_name', models.CharField(editable=False, max_length=10)),
                ('month', models.IntegerField(editable=False)),
                ('month_name', models.CharField(editable=False, max_length=10)),
                ('year', models.IntegerField(editable=False)),
                ('week_of_year', models.IntegerField(editable=False)),
                ('is_weekend', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall_management_system.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='mall_manage_created_c93b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='mall_manage_categor_03b132_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['hour'], name='mall_manage_hour_9f08f2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['day_of_week'], name='mall_manage_day_of__16dcc1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['month'], name='mall_manage_month_8edf6a_idx'),
        ),
    ]
