version: '3.8'

services:
  db:
    image: postgres:15
    container_name: mall_postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-mall_analytics_db}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secretpassword}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mall_network

  web:
    build: .
    container_name: mall_django_app
    restart: always
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - mall_network

volumes:
  postgres_data:

networks:
  mall_network: